name: Validate

on: [pull_request]

jobs:
  check_spec:

    runs-on: ubuntu-latest
    container:
      image: docker.io/library/rockylinux:8

    steps:
    - name: Setup
      run: |
        dnf install -y epel-release git python3
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Validate Changes
      run: |
        tests/ci/check_spec.py ${{ steps.files.outputs.added_modified }}

  build_on_openEuler:
    runs-on: ubuntu-latest
    container:
      image: docker.io/openeuler/openeuler:22.03-lts
    steps:
    - name: Setup
      run: |
        dnf install -y openEuler-release dnf-plugins-core git python3 findutils rpm-build wget gawk
        dnf install -y http://121.36.3.168:82/home:/huangtianhua:/ohpc/standard_x86_64/x86_64/ohpc-release-2-1.oe2203.ohpc.2.0.0.x86_64.rpm

        yum install -y lmod-ohpc
        adduser ohpc
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Validate Build
      run: |
        . /etc/profile.d/lmod.sh
        tests/ci/run_build.py ohpc ${{ steps.files.outputs.added_modified }}
